# Generated by Django 5.1.6 on 2025-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
