---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint Imbuto Backend
    runs-on: ubuntu-latest
    env:
      DB_HOST: db
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASS: changeme
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing Imbuto Backend
        run: docker-compose run --rm app sh -c "python check_db.py --service-name db --ip db --port 5432 && python manage.py test"
      - name: Verifying code integrity
        run: docker-compose run --rm app sh -c "flake8"
